name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19' # Specify your Go version here

      - name: Build
        run: |
          go build -o email.exe ./path/to/your/main.go # Adjust path as needed

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: email-executable
          path: email.exe
